# Generated by Django 4.2.1 on 2023-06-22 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(db_column='idDiagnostico', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(db_column='idMaterial', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(db_column='idTrabajo', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_diagnostico', models.ForeignKey(db_column='idDiagnostico', on_delete=django.db.models.deletion.CASCADE, to='app1.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='Material_trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_material', models.ForeignKey(db_column='idMaterial', on_delete=django.db.models.deletion.CASCADE, to='app1.material')),
                ('id_trabajo', models.ForeignKey(db_column='idTrabajo', on_delete=django.db.models.deletion.CASCADE, to='app1.trabajo')),
            ],
        ),
    ]
