# Generated by Django 4.2.1 on 2023-06-24 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_trabajo',
            name='id_material',
        ),
        migrations.RemoveField(
            model_name='material_trabajo',
            name='id_trabajo',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='id_diagnostico',
        ),
        migrations.DeleteModel(
            name='Diagnostico',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Material_trabajo',
        ),
        migrations.DeleteModel(
            name='Trabajo',
        ),
    ]
